---
title: "Voting patterns"
output: html_document
date: "2024-05-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(ggplot2)
library(tidyverse)
library(pastecs)
library(dplyr)
library(gridExtra)
library(stringi)
library(WRS2)
library(car)
library(readxl)
library(janitor)
library(fedmatch)#(https://cran.r-project.org/web/packages/fedmatch/vignettes/Fuzzy-matching.html)
library(broom)
library(knitr)
library(car)
library(dlookr)
library(flextable)
library(rstanarm)
library(performance)
```

#Load the data
```{r}
data <- read.csv("Data/dataset.csv")
Turtles1_16_80 <- read.csv("Data/CSV/TURTLES_1_16_80.csv")
Turtles2_16_80 <- read.csv("Data/CSV/TURTLES_2_16_80.csv")
Turtles3_16_80 <- read.csv("Data/CSV/TURTLES_3_16_80.csv")
Turtles4_16_80 <- read.csv("Data/CSV/TURTLES_4_16_80.csv")
Turtles5_16_80 <- read.csv("Data/CSV/TURTLES_5_16_80.csv")
Turtles1_16_100 <- read.csv("Data/CSV/TURTLES_1_16_100.csv")
Turtles2_16_100 <- read.csv("Data/CSV/TURTLES_2_16_100.csv")
Turtles3_16_100 <- read.csv("Data/CSV/TURTLES_3_16_100.csv")
Turtles4_16_100 <- read.csv("Data/CSV/TURTLES_4_16_100.csv")
Turtles5_16_100 <- read.csv("Data/CSV/TURTLES_5_16_100.csv")
Turtles1_18_80 <- read.csv("Data/CSV/TURTLES_1_18_80.csv")
Turtles2_18_80 <- read.csv("Data/CSV/TURTLES_2_18_80.csv")
Turtles3_18_80 <- read.csv("Data/CSV/TURTLES_3_18_80.csv")
Turtles4_18_80 <- read.csv("Data/CSV/TURTLES_4_18_80.csv")
Turtles5_18_80 <- read.csv("Data/CSV/TURTLES_5_18_80.csv")
Turtles1_18_100 <- read.csv("Data/CSV/TURTLES_1_18_100.csv")
Turtles2_18_100 <- read.csv("Data/CSV/TURTLES_2_18_100.csv")
Turtles3_18_100 <- read.csv("Data/CSV/TURTLES_3_18_100.csv")
Turtles4_18_100 <- read.csv("Data/CSV/TURTLES_4_18_100.csv")
Turtles5_18_100 <- read.csv("Data/CSV/TURTLES_5_18_100.csv")
Globals <- read.csv("Data/CSV/GLOBALS_1_16_80.csv")
Patches <- read.csv("Data/CSV/PATCHES_1_16_80.csv")
```

#Bind df together and add sim number
```{r}
Turtles1_16_80$sim <- 1
Turtles2_16_80$sim <- 2
Turtles3_16_80$sim <- 3
Turtles4_16_80$sim <- 4
Turtles5_16_80$sim <- 5
Turtles1_18_80$sim <- 1
Turtles2_18_80$sim <- 2
Turtles3_18_80$sim <- 3
Turtles4_18_80$sim <- 4
Turtles5_18_80$sim <- 5
Turtles1_16_100$sim <- 1
Turtles2_16_100$sim <- 2
Turtles3_16_100$sim <- 3
Turtles4_16_100$sim <- 4
Turtles5_16_100$sim <- 5
Turtles1_18_100$sim <- 1
Turtles2_18_100$sim <- 2
Turtles3_18_100$sim <- 3
Turtles4_18_100$sim <- 4
Turtles5_18_100$sim <- 5

df_16_80 <- rbind(Turtles1_16_80, Turtles2_16_80, Turtles3_16_80, Turtles4_16_80, Turtles5_16_80)
df_16_100 <- rbind(Turtles1_16_100, Turtles2_16_100, Turtles3_16_100, Turtles4_16_100, Turtles5_16_100)
df_18_80 <- rbind(Turtles1_18_80, Turtles2_18_80, Turtles3_18_80, Turtles4_18_80, Turtles5_18_80)
df_18_100 <- rbind(Turtles1_18_100, Turtles2_18_100, Turtles3_18_100, Turtles4_18_100, Turtles5_18_100)
```

# Visualizations
```{r}
grid.arrange(
  ggplot(df_16_80, aes(x = vote, fill = factor(sim))) +
  geom_histogram(binwidth = 1, color = "black", alpha = 0.7, position = "dodge") +
  labs(title = "Age 16-80", x = "Vote", y = "Frequency") +
  theme_minimal() +
  scale_fill_manual(values = c("red", "blue", "green", "purple", "orange")) +
  guides(fill = guide_legend(title = "Simulation")),
  
  ggplot(df_16_100, aes(x = vote, fill = factor(sim))) +
  geom_histogram(binwidth = 1, color = "black", alpha = 0.7, position = "dodge") +
  labs(title = "Age 16-100", x = "Vote", y = "Frequency") +
  theme_minimal() +
  scale_fill_manual(values = c("red", "blue", "green", "purple", "orange")) +
  guides(fill = guide_legend(title = "Simulation")),
  
  ggplot(df_18_80, aes(x = vote, fill = factor(sim))) +
  geom_histogram(binwidth = 1, color = "black", alpha = 0.7, position = "dodge") +
  labs(title = "Age 18-80", x = "Vote", y = "Frequency") +
  theme_minimal() +
  scale_fill_manual(values = c("red", "blue", "green", "purple", "orange")) +
  guides(fill = guide_legend(title = "Simulation")),
  
  ggplot(df_18_100, aes(x = vote, fill = factor(sim))) +
  geom_histogram(binwidth = 1, color = "black", alpha = 0.7, position = "dodge") +
  labs(title = "Age 18-100", x = "Vote", y = "Frequency") +
  theme_minimal() +
  scale_fill_manual(values = c("red", "blue", "green", "purple", "orange")) +
  guides(fill = guide_legend(title = "Simulation")),
  
  nrow = 2, ncol = 2
)
```

```{r}
grid.arrange(
ggplot(Turtles1_16_80, aes(x = vote)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black", alpha = 0.7) +
  labs(title = "Sim 1; 16-80", x = "Vote", y = "Frequency") +
  theme_minimal(),

ggplot(Turtles2_16_80, aes(x = vote)) +
  geom_histogram(binwidth = 1, fill = "red", color = "black", alpha = 0.7) +
  labs(title = "Sim 2; 16-80", x = "Vote", y = "Frequency") +
  theme_minimal(),

ggplot(Turtles3_16_80, aes(x = vote)) +
  geom_histogram(binwidth = 1, fill = "green4", color = "black", alpha = 0.7) +
  labs(title = "Sim 3; 16-80", x = "Vote", y = "Frequency") +
  theme_minimal(),

ggplot(Turtles4_16_80, aes(x = vote)) +
  geom_histogram(binwidth = 1, fill = "orange", color = "black", alpha = 0.7) +
  labs(title = "Sim 4; 16-80", x = "Vote", y = "Frequency") +
  theme_minimal(),

ggplot(Turtles5_16_80, aes(x = vote)) +
  geom_histogram(binwidth = 1, fill = "purple", color = "black", alpha = 0.7) +
  labs(title = "Sim 5; 16-80", x = "Vote", y = "Frequency") +
  theme_minimal(),

ggplot(Turtles1_16_100, aes(x = vote)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black", alpha = 0.7) +
  labs(title = "Sim 1; 16-100", x = "Vote", y = "Frequency") +
  theme_minimal(),

ggplot(Turtles2_16_100, aes(x = vote)) +
  geom_histogram(binwidth = 1, fill = "red", color = "black", alpha = 0.7) +
  labs(title = "Sim 2; 16-100", x = "Vote", y = "Frequency") +
  theme_minimal(),

ggplot(Turtles3_16_100, aes(x = vote)) +
  geom_histogram(binwidth = 1, fill = "green4", color = "black", alpha = 0.7) +
  labs(title = "Sim 3; 16-100", x = "Vote", y = "Frequency") +
  theme_minimal(),

ggplot(Turtles4_16_100, aes(x = vote)) +
  geom_histogram(binwidth = 1, fill = "orange", color = "black", alpha = 0.7) +
  labs(title = "Sim 4; 16-100", x = "Vote", y = "Frequency") +
  theme_minimal(),

ggplot(Turtles5_16_100, aes(x = vote)) +
  geom_histogram(binwidth = 1, fill = "purple", color = "black", alpha = 0.7) +
  labs(title = "Sim 5; 16-100", x = "Vote", y = "Frequency") +
  theme_minimal(),

ggplot(Turtles1_18_80, aes(x = vote)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black", alpha = 0.7) +
  labs(title = "Sim 1; 18-80", x = "Vote", y = "Frequency") +
  theme_minimal(),

ggplot(Turtles2_18_80, aes(x = vote)) +
  geom_histogram(binwidth = 1, fill = "red", color = "black", alpha = 0.7) +
  labs(title = "Sim 2; 18-80", x = "Vote", y = "Frequency") +
  theme_minimal(),

ggplot(Turtles3_18_80, aes(x = vote)) +
  geom_histogram(binwidth = 1, fill = "green4", color = "black", alpha = 0.7) +
  labs(title = "Sim 3; 18-80", x = "Vote", y = "Frequency") +
  theme_minimal(),

ggplot(Turtles4_18_80, aes(x = vote)) +
  geom_histogram(binwidth = 1, fill = "orange", color = "black", alpha = 0.7) +
  labs(title = "Sim 4; 18-80", x = "Vote", y = "Frequency") +
  theme_minimal(),

ggplot(Turtles5_18_80, aes(x = vote)) +
  geom_histogram(binwidth = 1, fill = "purple", color = "black", alpha = 0.7) +
  labs(title = "Sim 5; 18-80", x = "Vote", y = "Frequency") +
  theme_minimal(),

ggplot(Turtles1_18_100, aes(x = vote)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black", alpha = 0.7) +
  labs(title = "Sim 1; 18-100", x = "Vote", y = "Frequency") +
  theme_minimal(),

ggplot(Turtles2_18_100, aes(x = vote)) +
  geom_histogram(binwidth = 1, fill = "red", color = "black", alpha = 0.7) +
  labs(title = "Sim 2; 18-100", x = "Vote", y = "Frequency") +
  theme_minimal(),

ggplot(Turtles3_18_100, aes(x = vote)) +
  geom_histogram(binwidth = 1, fill = "green4", color = "black", alpha = 0.7) +
  labs(title = "Sim 3; 18-100", x = "Vote", y = "Frequency") +
  theme_minimal(),

ggplot(Turtles4_18_100, aes(x = vote)) +
  geom_histogram(binwidth = 1, fill = "orange", color = "black", alpha = 0.7) +
  labs(title = "Sim 4; 18-100", x = "Vote", y = "Frequency") +
  theme_minimal(),

ggplot(Turtles5_18_100, aes(x = vote)) +
  geom_histogram(binwidth = 1, fill = "purple", color = "black", alpha = 0.7) +
  labs(title = "Sim 5; 18-100", x = "Vote", y = "Frequency") +
  theme_minimal(),

nrow = 4, ncol = 5

)
```
#Data analysis

Modelling spread of vote for default age range 18-100
```{r}
# Descriptive Statistics
summary(df_18_100$vote)
mean(df_18_100$vote)
median(df_18_100$vote)
var(df_18_100$vote)
sd(df_18_100$vote)

grid.arrange(
# Histogram
ggplot(df_18_100, aes(x = vote)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black", alpha = 0.7) +
  labs(title = "Histogram of Votes", x = "Vote", y = "Frequency") +
  theme_minimal(),

# Box Plot
ggplot(df_18_100, aes(y = vote)) +
  geom_boxplot(fill = "blue", color = "black", alpha = 0.7) +
  labs(title = "Box Plot of Votes", y = "Vote") +
  theme_minimal(),

# Density Plot
ggplot(df_18_100, aes(x = vote)) +
  geom_density(fill = "blue", color = "black", alpha = 0.7) +
  labs(title = "Density Plot of Votes", x = "Vote", y = "Density") +
  theme_minimal(),

# Violin Plot
ggplot(df_18_100, aes(x = factor(1), y = vote)) +
  geom_violin(fill = "blue", color = "black", alpha = 0.7) +
  labs(title = "Violin Plot of Votes", x = "", y = "Vote") +
  theme_minimal() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()),

nrow = 2, ncol = 2

)
```

