---
title: "Test R code"
output: html_document
date: "2024-05-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(ggplot2)
library(tidyverse)
library(pastecs)
library(dplyr)
library(gridExtra)
library(stringi)
library(WRS2)
library(car)
library(readxl)
library(janitor)
library(fedmatch)#(https://cran.r-project.org/web/packages/fedmatch/vignettes/Fuzzy-matching.html)
library(broom)
library(knitr)
library(car)
library(dlookr)
library(flextable)
library(rstanarm)
library(performance)
```

## Load data
```{r}
Turtles1_16_80 <- read.csv("Data/CSV/TURTLES_1_16_80.csv")
Turtles2_16_80 <- read.csv("Data/CSV/TURTLES_2_16_80.csv")
Turtles3_16_80 <- read.csv("Data/CSV/TURTLES_3_16_80.csv")
Turtles4_16_80 <- read.csv("Data/CSV/TURTLES_4_16_80.csv")
Turtles5_16_80 <- read.csv("Data/CSV/TURTLES_5_16_80.csv")
Turtles6_16_80 <- read.csv("Data/CSV/TURTLES_6_16_80.csv")
Turtles7_16_80 <- read.csv("Data/CSV/TURTLES_7_16_80.csv")
Turtles8_16_80 <- read.csv("Data/CSV/TURTLES_8_16_80.csv")
Turtles9_16_80 <- read.csv("Data/CSV/TURTLES_9_16_80.csv")
Turtles10_16_80 <- read.csv("Data/CSV/TURTLES_10_16_80.csv")
Turtles1_16_100 <- read.csv("Data/CSV/TURTLES_1_16_100.csv")
Turtles2_16_100 <- read.csv("Data/CSV/TURTLES_2_16_100.csv")
Turtles3_16_100 <- read.csv("Data/CSV/TURTLES_3_16_100.csv")
Turtles4_16_100 <- read.csv("Data/CSV/TURTLES_4_16_100.csv")
Turtles5_16_100 <- read.csv("Data/CSV/TURTLES_5_16_100.csv")
Turtles6_16_100 <- read.csv("Data/CSV/TURTLES_6_16_100.csv")
Turtles7_16_100 <- read.csv("Data/CSV/TURTLES_7_16_100.csv")
Turtles8_16_100 <- read.csv("Data/CSV/TURTLES_8_16_100.csv")
Turtles9_16_100 <- read.csv("Data/CSV/TURTLES_9_16_100.csv")
Turtles10_16_100 <- read.csv("Data/CSV/TURTLES_10_16_100.csv")
Turtles1_18_80 <- read.csv("Data/CSV/TURTLES_1_18_80.csv")
Turtles2_18_80 <- read.csv("Data/CSV/TURTLES_2_18_80.csv")
Turtles3_18_80 <- read.csv("Data/CSV/TURTLES_3_18_80.csv")
Turtles4_18_80 <- read.csv("Data/CSV/TURTLES_4_18_80.csv")
Turtles5_18_80 <- read.csv("Data/CSV/TURTLES_5_18_80.csv")
Turtles6_18_80 <- read.csv("Data/CSV/TURTLES_6_18_80.csv")
Turtles7_18_80 <- read.csv("Data/CSV/TURTLES_7_18_80.csv")
Turtles8_18_80 <- read.csv("Data/CSV/TURTLES_8_18_80.csv")
Turtles9_18_80 <- read.csv("Data/CSV/TURTLES_9_18_80.csv")
Turtles10_18_80 <- read.csv("Data/CSV/TURTLES_10_18_80.csv")
Turtles1_18_100 <- read.csv("Data/CSV/TURTLES_1_18_100.csv")
Turtles2_18_100 <- read.csv("Data/CSV/TURTLES_2_18_100.csv")
Turtles3_18_100 <- read.csv("Data/CSV/TURTLES_3_18_100.csv")
Turtles4_18_100 <- read.csv("Data/CSV/TURTLES_4_18_100.csv")
Turtles5_18_100 <- read.csv("Data/CSV/TURTLES_5_18_100.csv")
Turtles6_18_100 <- read.csv("Data/CSV/TURTLES_6_18_100.csv")
Turtles7_18_100 <- read.csv("Data/CSV/TURTLES_7_18_100.csv")
Turtles8_18_100 <- read.csv("Data/CSV/TURTLES_8_18_100.csv")
Turtles9_18_100 <- read.csv("Data/CSV/TURTLES_9_18_100.csv")
Turtles10_18_100 <- read.csv("Data/CSV/TURTLES_10_18_100.csv")
```

